# -*- coding: utf-8 -*-
"""dna_complement_bonds.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFpTSqh9JkTzFxtMDvuHFkG9ky4Y62rD
"""

!pip install biopython
from Bio.Seq import Seq
DNA_Seq=("ATGCTGATCGTTTAAGTC")
complement=("TACGACTAGCAAATTCAG")
bond=""
for d ,s in zip(DNA_Seq,complement):
 if (d=="T" and s=="A")or(s=="T" and d=="A")\
or(d=="G"  and s=="C")or(s=="C" and d=="G"):
  bond += " | "
else:
  bond += "   "
print("5'-"  , "  ".join(DNA_Seq) ,  "3'-")
print("  "   , (bond)  )
print("3'-"  , "  ".join(complement) ,  "5'-")
# protein=DNA.translate()
# print(protein)
# tran=(DNA.transcribe())
# print("5'",tran,"3'")